version: '3'
services:
  api:
    hostname: simple-storage.local
    container_name: simple-storage-api
    links:
      - mysql
    ports:
      - 8081:8080
    build: ./
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/simple_storage?useSSL=false
      SPRING_DATASOURCE_username: root
      SPRING_DATASOURCE_password: root
  mysql:
    image: mysql:5.7
    hostname: mysql.local
    container_name: simple-storage-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_storage
  liquibase:
    build: migration
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      JDBC_MASTER_URL: jdbc:mysql://mysql/simple_storage?useSSL=false
      JDBC_MASTER_USERNAME: root
      JDBC_MASTER_PASSWORD: root